FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod ./
COPY internal ./internal
COPY cmd/storage ./cmd/storage
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o rx-storage ./cmd/storage

FROM alpine:3.19
RUN apk --no-cache add ca-certificates curl
WORKDIR /app
COPY --from=builder /app/rx-storage .
EXPOSE 8083
ENTRYPOINT ["/app/rx-storage"]
