FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod ./
COPY internal ./internal
COPY cmd/security ./cmd/security
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o rx-security ./cmd/security

FROM alpine:3.19
RUN apk --no-cache add ca-certificates curl
WORKDIR /app
COPY --from=builder /app/rx-security .
EXPOSE 8081
ENTRYPOINT ["/app/rx-security"]
