FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod ./
COPY internal ./internal
COPY cmd/delivery ./cmd/delivery
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o rx-delivery ./cmd/delivery

FROM alpine:3.19
RUN apk --no-cache add ca-certificates curl
WORKDIR /app
COPY --from=builder /app/rx-delivery .
EXPOSE 8087
ENTRYPOINT ["/app/rx-delivery"]
