FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod ./
COPY internal ./internal
COPY cmd/reader ./cmd/reader
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o rx-reader ./cmd/reader

FROM alpine:3.19
RUN apk --no-cache add ca-certificates curl
WORKDIR /app
COPY --from=builder /app/rx-reader .
EXPOSE 8085
ENTRYPOINT ["/app/rx-reader"]
