FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod ./
COPY internal ./internal
COPY cmd/audit ./cmd/audit
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o rx-audit ./cmd/audit

FROM alpine:3.19
RUN apk --no-cache add ca-certificates curl
WORKDIR /app
COPY --from=builder /app/rx-audit .
EXPOSE 8088
ENTRYPOINT ["/app/rx-audit"]
