FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod ./
COPY internal ./internal
COPY cmd/study ./cmd/study
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o rx-study ./cmd/study

FROM alpine:3.19
RUN apk --no-cache add ca-certificates curl
WORKDIR /app
COPY --from=builder /app/rx-study .
EXPOSE 8082
ENTRYPOINT ["/app/rx-study"]
