FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod ./
COPY internal ./internal
COPY cmd/image ./cmd/image
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o rx-image ./cmd/image

FROM alpine:3.19
RUN apk --no-cache add ca-certificates curl
WORKDIR /app
COPY --from=builder /app/rx-image .
EXPOSE 8084
ENTRYPOINT ["/app/rx-image"]
